# android/app-config.properties
applicationId=excellentminds.newGetxCLI
appName=Base-Project
minSdk=24
targetSdk=36

versionCode=1
versionName=0.0.1

dev.versionCode=20
dev.versionName=1.0.0-dev

stage.versionCode=30
stage.versionName=1.0.0-stage

prod.versionCode=50
prod.versionName=1.0.0
