// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMeFLDEMIBCPXc3HeuRJJ3Sm3hkkLX-wY',
    appId: '1:287559879272:web:a8074bad94a9f27a38c9dd',
    messagingSenderId: '287559879272',
    projectId: 'baseproject-e46cf',
    authDomain: 'baseproject-e46cf.firebaseapp.com',
    storageBucket: 'baseproject-e46cf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3hp8vv-Jwhk9u-ECSEhlTDQdVUBBkfh8',
    appId: '1:287559879272:android:b0064bd397b2637438c9dd',
    messagingSenderId: '287559879272',
    projectId: 'baseproject-e46cf',
    storageBucket: 'baseproject-e46cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD24w35HMKRXgNiORB7E_FOq1jTlCIuZkM',
    appId: '1:287559879272:ios:fda5b07ba981f76f38c9dd',
    messagingSenderId: '287559879272',
    projectId: 'baseproject-e46cf',
    storageBucket: 'baseproject-e46cf.firebasestorage.app',
    iosBundleId: 'excellentmindsnewGetxCLI',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD24w35HMKRXgNiORB7E_FOq1jTlCIuZkM',
    appId: '1:287559879272:ios:a71cb364634c954f38c9dd',
    messagingSenderId: '287559879272',
    projectId: 'baseproject-e46cf',
    storageBucket: 'baseproject-e46cf.firebasestorage.app',
    iosBundleId: 'com.example.ermHrms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMeFLDEMIBCPXc3HeuRJJ3Sm3hkkLX-wY',
    appId: '1:287559879272:web:a7c186f076218ad438c9dd',
    messagingSenderId: '287559879272',
    projectId: 'baseproject-e46cf',
    authDomain: 'baseproject-e46cf.firebaseapp.com',
    storageBucket: 'baseproject-e46cf.firebasestorage.app',
  );
}
